### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by WiseBird** [cedx/lcov.js#1]
Hello Cédric
Thank you a lot for the package!

A quick question if you don't mind.
I saw you ported the library from Typescript to Javascript and then back. What was the reason? Just curious.

**Comment by CedX** [comment]
Because I like wasting my time and energy!
On a more serious note, I have a somewhat conflicted relationship with TypeScript: I don't particularly like it, and I hate going through the compilation phase.

That's why I switched to JavaScript and JSDoc annotations on all my projects.
After a long time (1 year, 2 years?), I realized that this hadn't brought any improvement: the JSDoc syntax is much more limited (non-null assertion operator is not supported for example), and I still have to compile the code to extract the type declarations.

...So I went back to TypeScript 🙃
